/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * Secure Communication Framework is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan
 * PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */


#ifndef SCF_ERRNO_H
#define SCF_ERRNO_H

#ifdef __cplusplus
extern "C" {
#endif

/**
* @ingroup sdf_SCF_errno
* @brief   SCF 返回成功
*/
#define SCF_SUCCESS 0

/**
* @ingroup sdf_SCF_errno
* @brief   SCF 返回失败
*/
#define SCF_ERROR 1

/**
* @ingroup sdf_SCF_errno
* @brief   SCF ID 号
*/
#define SCF_PROJECT_ID 0x75000000

#define SCF_MOD_MAKE(Mod) (SCF_PROJECT_ID | ((uint32_t)(Mod) << 8UL))

#define SCF_MOD_COMMON SCF_MOD_MAKE(0x0000)
#define SCF_MOD_CAL SCF_MOD_MAKE(0x0010)
#define SCF_SUBMOD_SSL_RETRY SCF_MOD_MAKE(0x0020)
#define SCF_SUBMOD_SSL SCF_MOD_MAKE(0x0021)
#define SCF_MOD_CONFIG SCF_MOD_MAKE(0x0011)
#define SCF_MOD_LOG SCF_MOD_MAKE(0x9000)

/**
* @ingroup sdf_SCF_errno
* @brief   构造错误码的宏
* @param  Mod 模块ID
* @param  Errno 错误原因 0x0000 - 0x0FFF
*/
#define SCF_ERRNO_MAKE(Mod, Errno) ((Mod) | (Errno))

/************************* 错误码起始 *******************************/
// 通用错误码
#define SCF_ERRNO_NULL_INPUT        SCF_ERRNO_MAKE(SCF_MOD_COMMON, 1)   // 空指针入参  0x75000001 1962934273
#define SCF_ERRNO_INVALID_PARAM     SCF_ERRNO_MAKE(SCF_MOD_COMMON, 2)   // 无效入参
#define SCF_ERRNO_MEM_ALLOC         SCF_ERRNO_MAKE(SCF_MOD_COMMON, 3)   // 内存申请失败
#define SCF_ERRNO_MEM_CPY           SCF_ERRNO_MAKE(SCF_MOD_COMMON, 4)   // 内存拷贝失败
#define SCF_ERRNO_NOT_SUPPORT       SCF_ERRNO_MAKE(SCF_MOD_COMMON, 5)   // 仅预留参数，未实际实现的功能
#define SCF_ERRNO_INIT_BSM          SCF_ERRNO_MAKE(SCF_MOD_COMMON, 6)   // 初始化失败，sdf bsm 模块
#define SCF_ERRNO_LARGE_FILE        SCF_ERRNO_MAKE(SCF_MOD_COMMON, 7)   // 读取超大文件
#define SCF_ERRNO_SYSTEM_TIME_ERROR SCF_ERRNO_MAKE(SCF_MOD_COMMON, 8)   // 获取系统时间异常
#define SCF_ERRNO_FILE_PATH_ERROR   SCF_ERRNO_MAKE(SCF_MOD_COMMON, 9)   // 获取文件路径异常
#define SCF_ERRNO_READ_FILE_ERROR   SCF_ERRNO_MAKE(SCF_MOD_COMMON, 10)   // 获取文件异常

// CAL 模块
#define SCF_ERRNO_INIT_HITLS_BSL      SCF_ERRNO_MAKE(SCF_MOD_CAL, 1)   // 初始化失败，hitls bsl 模块 0x75001001 1962938369
#define SCF_ERRNO_INIT_HITLS_CRYPTO   SCF_ERRNO_MAKE(SCF_MOD_CAL, 2)   // 初始化失败，hitls crypto 模块
#define SCF_ERRNO_INIT_HITLS_TLS      SCF_ERRNO_MAKE(SCF_MOD_CAL, 3)   // 初始化失败，hitls tls 模块
#define SCF_ERRNO_NULL_HITLS_CTX      SCF_ERRNO_MAKE(SCF_MOD_CAL, 4)
#define SCF_ERRNO_NULL_HITLS_CFG      SCF_ERRNO_MAKE(SCF_MOD_CAL, 5)
#define SCF_ERRNO_SECURE_TRANSPORT    SCF_ERRNO_MAKE(SCF_MOD_CAL, 6)
#define SCF_ERRNO_INIT_OPENSSL        SCF_ERRNO_MAKE(SCF_MOD_CAL, 7)
#define SCF_ERRNO_INIT_OPENSSL_ERR    SCF_ERRNO_MAKE(SCF_MOD_CAL, 8)
#define SCF_ERRNO_INIT_OPENSSL_CRYPTO SCF_ERRNO_MAKE(SCF_MOD_CAL, 9)
#define SCF_ERRNO_INIT_OPENSSL_ALGO   SCF_ERRNO_MAKE(SCF_MOD_CAL, 10)
#define SCF_ERRNO_NULL_CALLBACK       SCF_ERRNO_MAKE(SCF_MOD_CAL, 11)
#define SCF_ERRNO_TLS_ALREADY_INIT    SCF_ERRNO_MAKE(SCF_MOD_CAL, 12)
#define SCF_ERRNO_INVALID_TLS_TYPE    SCF_ERRNO_MAKE(SCF_MOD_CAL, 13)
#define SCF_ERRNO_LOAD_LIB            SCF_ERRNO_MAKE(SCF_MOD_CAL, 14)
#define SCF_ERRNO_UNLOAD_LIB          SCF_ERRNO_MAKE(SCF_MOD_CAL, 15)
#define SCF_ERRNO_LOAD_SYMBOL         SCF_ERRNO_MAKE(SCF_MOD_CAL, 16)
#define SCF_ERRNO_INIT_HITLS_PSE      SCF_ERRNO_MAKE(SCF_MOD_CAL, 17)   // 初始化失败，hitls pse 模块
#define SCF_ERRNO_INIT_SECUREC        SCF_ERRNO_MAKE(SCF_MOD_CAL, 18)   // 初始化失败，securec 模块
#define SCF_ERRNO_NOT_INIT            SCF_ERRNO_MAKE(SCF_MOD_CAL, 19)   // 未初始化

// CONFIG 模块
#define SCF_CFG_ERRNO_PARSE                   SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 1) // 0x75001101  1962938625
#define SCF_CFG_ERRNO_CERT_ARRAY_GET          SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 2)
#define SCF_CFG_ERRNO_CERT_ITEM_GET           SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 3)
#define SCF_CFG_ERRNO_CERT_ADD                SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 4)
#define SCF_CFG_ERRNO_PRIVKEY_GET             SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 5)
#define SCF_CFG_ERRNO_PRIVKEY_ADD             SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 6)
#define SCF_CFG_ERRNO_CIPHER_SUITES_ARRAY_GET SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 7)
#define SCF_CFG_ERRNO_CIPHER_SUITES_ITEM_GET  SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 8)
#define SCF_CFG_ERRNO_TLS_VERSION_GET         SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 9)
#define SCF_CFG_ERRNO_TLS_VERSION_SET         SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 10)
#define SCF_CFG_ERRNO_TLS_FORBID_VERSION_GET  SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 11)
#define SCF_CFG_ERRNO_KEY_UPDATE              SCF_ERRNO_MAKE(SCF_MOD_CONFIG, 12)

// SSL 实现，对应 ssl 可重新尝试的状态(1 - 256分段)
#define SCF_SSL_ERR_SSL                  SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 1) // 0x75002001 1962942465
#define SCF_SSL_ERR_WANT_READ            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 2)
#define SCF_SSL_ERR_WANT_WRITE           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 3)
#define SCF_SSL_ERR_WANT_X509_LOOKUP     SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 4)
#define SCF_SSL_ERR_SYSCALL              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 5)
#define SCF_SSL_ERR_ZERO_RETURN          SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 6)
#define SCF_SSL_ERR_WANT_CONNECT         SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 7)
#define SCF_SSL_ERR_WANT_ACCEPT          SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 8)
#define SCF_SSL_ERR_WANT_ASYNC           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 9)
#define SCF_SSL_ERR_WANT_ASYNC_JOB       SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 10)
#define SCF_SSL_ERR_WANT_CLIENT_HELLO_CB SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 11)
#define SCF_SSL_ERR_WANT_BACKEP          SCF_ERRNO_MAKE(SCF_SUBMOD_SSL_RETRY, 12)
// SSL 实现
#define SCF_SSL_ERR_FORMAT_TYPE           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 1) // 0x75002101 1962942721
#define SCF_SSL_ERR_STORE_TYPE            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 2)
#define SCF_SSL_ERR_PARSE_CERT            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 3)
#define SCF_SSL_ERR_ADD_CERT_TO_STORE     SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 4)
#define SCF_SSL_ERR_LOAD_KEY              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 5)
#define SCF_SSL_ERR_PATH_TOO_LONG         SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 6)
#define SCF_SSL_ERR_CHECK_PKEY            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 7)
#define SCF_SSL_ERR_ROLE                  SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 8)
#define SCF_SSL_ERR_INIT_TLS13            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 9)
#define SCF_SSL_ERR_PSK_CB_HASH           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 10)
#define SCF_SSL_ERR_GET_VERSION           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 11)
#define SCF_SSL_ERR_PSK_MISMATCH          SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 12)
#define SCF_SSL_ERR_VERSION               SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 13)
#define SCF_SSL_ERR_POLICY_VERSION        SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 14)
#define SCF_SSL_ERR_SET_PASS              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 15)
#define SCF_SSL_ERR_PARSE_KEY             SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 16)
#define SCF_SSL_ERR_LOAD_CRL              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 17)
#define SCF_SSL_ERR_SET_ROLE              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 18)
#define SCF_SSL_ERR_SESS_SET_CIPHER       SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 19)
#define SCF_SSL_ERR_SESS_SET_KEY          SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 20)
#define SCF_SSL_ERR_SESS_SET_PROTOCOL_VER SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 21)
#define SCF_SSL_ERR_READ                  SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 22)
#define SCF_SSL_ERR_WRITE                 SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 23)
#define SCF_SSL_ERR_CLOSE                 SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 24)
#define SCF_SSL_ERR_SET_CIPHER            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 25)
#define SCF_SSL_ERR_SET_PROTOCOL_VER      SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 26)
#define SCF_SSL_ERR_SET_VER_FORBID        SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 27)
#define SCF_SSL_ERR_GET_CIPHER            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 28)
#define SCF_SSL_ERR_ADD_CA_CERT_TO_STORE  SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 29)
#define SCF_SSL_ERR_ADD_EE_CERT_TO_STORE  SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 30)
#define SCF_SSL_ERR_ADD_CRL_TO_STORE      SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 31)
#define SCF_SSL_ERR_INIT_TLS              SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 32)
#define SCF_SSL_ERR_SET_SEC_LEVEL         SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 33)
#define SCF_SSL_ERR_SET_SESS_TICKET       SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 34)
#define SCF_SSL_ERR_SET_SOCKET_FD         SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 35)
#define SCF_SSL_ERR_SEC_LEVEL_MISMATCH    SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 36)
#define SCF_SSL_ERR_GET_CERT_STORE        SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 37)
#define SCF_SSL_ERR_KEY_UPDATE            SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 38)
#define SCF_SSL_ERR_IS_INIT_FINISHED      SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 39)
#define SCF_SSL_ERR_SET_UPDATE_PARAM      SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 40)
#define SCF_SSL_ERR_SET_CRL_CHECK_FLAGS   SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 41)
#define SCF_SSL_ERR_LOAD_CA_CERT_CHAIN    SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 42)
#define SCF_SSL_ERR_ADD_EE_CHAIN_TO_STORE SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 43)
#define SCF_SSL_ERR_X509_VERIFY_CHAIN     SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 44)
#define SCF_SSL_ERR_SET_EX_DATA           SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 45)
#define SCF_SSL_ERR_SESS_GET_CIPHER       SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 46)
#define SCF_SSL_ERR_SESS_GET_PROTOCOL_VER SCF_ERRNO_MAKE(SCF_SUBMOD_SSL, 47)

#ifdef __cplusplus
}
#endif

#endif